version: '3.8'
services:

  nginx:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 120s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${TRAEFIK_HOST}`)"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=to-https@file"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${TRAEFIK_HOST}`)"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=secure-headers@file"
        - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=lets-encrypt"
